name: allcools
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python=3.8
    - pip
    - anndata
    - biopython
    - dask
    - numba
    - flox
    - htslib>=1.9
    - jupyter
    - jupyter_contrib_nbextensions
    - leidenalg
    - natsort
    - networkx
    - opentsne
    - plotly
    - pybedtools
    - pyBigWig
    - pynndescent
    - pysam
    - pytables
    - scanpy
    - scikit-learn
    - seaborn
    - statsmodels
    - xarray
    - yaml
    - zarr
    - pip:
          - papermill
          - imblearn
          - allcools
